### ISSUE TITLE
Support iaspecname Canoncial Names

### ISSUE THREAD

**Issue by kingargyle** [lvisintini/imperial-assault-data#7]
I'm looking at using the imperial-assault-data files within XStreamer and a possible Android application.  One thing that would help is the ability to reference the data in the deployment cards and the command cards, by the iaspecName.   This will allow for easy reference for the iaspecname format that XStreamer and TableTop admiral support.    The Canonical name is pretty straight forward, and is documented here:

https://github.com/kingargyle/iaskirmish-data/wiki/Canonical-Names

Having this would allow exporting of data from Tabletop admiral, importing the squad into XStreamer (or vassal if it supports it), and then referencing it via the specname to the deployment and command card data you have created.

**Comment by lvisintini** [comment]
Hey @kingargyle, that seems fairly straightforward to accomplish
I will see about adding those data points in the next few days :+1:

**Comment by kingargyle** [comment]
Yeah it isn't difficult, just a bit time consuming to enter the data.

**Comment by rdkoehlinger** [comment]
Hello!

I noticed that the "Canonical Names" list misspelled "Kashyyyk" on the Fury of Kashyyyk card.  Both the name in the "Card Name" column and the "Canonical Name" column are misspelled (should be three ys instead of two).

Also, I'm wondering about your choices for the format.  My preference would be to use a format that would be as open and available for easy addition with new expansions as possible, as well as if people wanted to do similar work with campaign stuff.

To be honest, I think the formatting that @lvisintini has used is really effective and clear (minus the dashes).  I think we want this to be as clear and precise as possible to help with people who would want to work on programs, etc. in the future, and avoid all possible sources of confusion for coding (if you're like me, you can end up making really stupid mistakes that cause bugs that would have been avoided if I had labelled things more clearly).  Here are some suggestions:

1) I might put the "elite" string at the end of the name instead of the beginning, that way cards get grouped together alphabetically for the same unit, and for ease of thinking with human logic flow (this may be just me, but I tend to think about the card itself, then whether or not its an elite or regular version).

2) Add the elite string to things that there isn't a regular version for it (e.g. Bantha Rider, AT-DP) for consistency of logic (seeing as how you can only deploy two of those units, since they are technically elite)

3) Somehow specify when a card is only used in Skirmish.  For example, there are skirmish vs. campaign versions of cards, and not just characters like Jabba or Leia, but also the FFG created heroes for the campaign (since they operate very differently and have different things elements for campaign versus skirmish).  I'm not exactly sure how high-level this canonical-naming system is, so maybe this is a moot point where it will be further clarified in the data called by the canonical name (e.g. the canonical name "lukeskywalker" returns all versions of Luke (Farmboy and Jedi), "jabbathehutt" returns both the campaign and skirmish versions).  This may make the next point moot as well:

4) Canonical names should include the "sub-name" (or whatever you call it) for each unique figure.  That way it is really clear and easy to identify which card is being referenced in the future if FFG decides to make more versions of the same character (e.g. Farmboy Luke and Jedi Luke cards).

Thoughts?

**Comment by valeriodigregorio** [comment]
Numeric UIDs is the way to go. Great job @lvisintini. I wish TTAdmiral used this data model. I wanted to achieve a portable URI to import/export skirmish lists from ttadmiral to other apps.

**Comment by kingargyle** [comment]
The format is based off the xws-spec, https://github.com/elistevens/xws-spec.   This is a standard format used in X-Wing squad builders. 

The Canonical name format follows the format described here.

https://github.com/elistevens/xws-spec/blob/master/README_NAMES.md

The numeric ids, are more difficult from an interchange format perspective.  It ties the implementation to a specific ID, which may need to be specific to a particular system.  It is why I avoided it (ran into this numerous times when working on Data specification standards for XML).

I agree that the iaskirmish format should include the faction, to go along with the canonical name, the canonical name isn't enough on it's own to look things up.  Neither is it in X-Wing.

Also if you find spelling mistakes in the list, feel free to open issues on the iaskirmish projects site and I'll correct them.   I totally expect this to evolve but want to keep backwards compatiblity as much as we can.

**Comment by lvisintini** [comment]
I have had a few hours to work on this now and I have comments:

@rdkoehlinger:
I agree with you in that having `elite` at the end will be nicer, but if we want people to buy into using this data set, then we have to make it as easy as possible to adopt it.
Though the iaspec lacks "finesse" at the moment, it is the "de facto" standard and deviating a lot from it would hurt this project, and I lean towards adding them to the end.

Your other 3 points are good. I like all three and I have taken them into account on my tinkering.

@valeriodigregorio I like the unique integer ids as well, but if you use them, then any project using them will be tightly coupled with this project.

Also, having a proper standard allows for import/export of data between applications much more reliable and extensible.

I find that having canonical names and unique integer ids is not mutually exclusive, so I basically agree with you and also with @kingargyle 

----------------

## Proposed iaspec change

### Definition

- Canonical names are unique across the whole dataset. (we could do away with this if it is problematic down the like, but for the moment it is easily achieved)
- Canonical names only use alphanumerical characters in lower case (no spaces allowed)

- To get a canonical name for a particular component, there are 4 strategies:
    1. Use **elite** and **name** values
    1. Use **elite**, **name** and **game mode** values.
    1. Use **elite**, **name** and **affiliation** values.
    1. Use **elite**, **name** and **description** values.

- If an entry does not have a given value, or that values is `null` or `false`, don't add anything to the canonical name.
- If an entry's value is set to `true`, then add that value's name to the canonical name, except in the case of *elite* (see below)
- If an user has ``entry.elite == true``, only add `'elite'` to the canonical name if  ``entry.unique == false``
- If a entry's value references an array of other elements, only add to the name if that array has only 1 element. Example: (Only add `'skirmish'` or `'campaign'` to the canonical name if `entry.modes.length == 1`)


### Procedure

1. You take all entries that are going to need canonical names (regardless of type) and you define canonical names as an empty string. (just to begin with, we will change)
1. Run the strategies in ascending order and do the following:
    1. You take all the entries that share the same canonical name and use the current strategy to get new canonical names
    1. All the entries that do not have duplicates are taken out of this loop and no longer tampered with.
    1. Go back to step 2.ii using the next strategy.
1. If we continue to have duplicated canonical names, then this specification needs to further adapt to accommodate for the additional edge cases 

I have abstracted this in some code, but it is not the easiest to read at the moment.

### Results
Using the above I'm able to match 93.53% of the canonical names currently in [iaskirmish-data](https://github.com/kingargyle/iaskirmish-data) (340 unique names)

This are the mismatches:

iaspec | proposed | notes
------ | -------- | -----
lukeskywalkerjedi | lukeskywalkerjediknight | Needs renaming to use the description/tag line
lukeskywalker | lukeskywalkerherooftherebellion, lukeskywalkerjediknight | Needs desambiguation
leiaorgana | leiaorganacampaign, leiaorganaskirmish | Needs desambiguation
obiwankenobi | obiwankenobiskirmish, obiwankenobicampaign | Needs desambiguation
r2d2 | r2d2campaign, r2d2skirmish | Needs desambiguation
furyofkashyyk | furyofkashyyyk | There is a typo in iaskirmish-data
atst | eliteatst | Needs to accomodate for the fact that there could be a regular variant
sc2mrepulsortank | elitesc2mrepulsortank | Needs to accomodate for the fact that there could be a regular variant
atdp | eliteatdp | Needs to accomodate for the fact that there could be a regular variant
agentblaise | agentblaisecampaign, agentblaiseskirmish | Needs desambiguation
dewbackrider | elitedewbackrider | Needs to accomodate for the fact that there could be a regular variant
riottrooper | riottroopercampaign, riottrooperskirmish, eliteriottroopercampaign, eliteriottrooperskirmish | Needs desambiguation
crosstraining | elitecrosstraining | Needs to accomodate for the fact that there could be a regular variant
temporaryallianceempire | temporaryalliancemercenary, temporaryallianceimperial | Needs renaming (Imperial deployment, Mercenary deployment, Rebel deployment)
rancor | eliterancorcampaign, eliterancorskirmish | Needs to accomodate for the fact that there could be a regular variant
bantharider | elitebantharider | Needs to accomodate for the fact that there could be a regular variant
bossk | bosskmercenary, bosskrebel | Needs desambiguation
jabbathehutt | jabbathehuttcampaign, jabbathehuttskirmish | Needs desambiguation
elitejawascavenger | jawascavenger, elitejawascavengercampaign, elitejawascavengerskirmish | Needs to accommodate for 3 versions
tempoaryalliancescum | None | There is a typo in iaskirmish-data
feedingfrenzy | elitefeedingfrenzy |  Needs to accomodate for the fact that there could be a regular variant
sarlacsweep | sarlaccsweep | There is a typo in iaskirmish-data

Is this good enough? Comments?

**Comment by valeriodigregorio** [comment]
I like your proposal for rationalisation of iaspec. Being able to retrieve it from other metadata is definitely needed.

My proposal of numeric UIDs comes the from need of converting a list into a numerical encode that can be used in an URL and converted back to a list. You can't encode/decode strings easily for such a purpose and at the same time keep the size of the URL short.

On the other hands I understand that a standard mapping "iaspec <=> numerical UIDs" is still possible as an adaptation layer built on top of the data model. This could ensure interoperability. De facto standard for numerical UIDs is TTAdmiral at the moment because it's the unique web service that encode/decode lists into/from URLs.

I believe URLs and QR codes are a much better way to share lists among people, at tournaments, on forums and across different applications. I imagine people displaying a QR code on their phone and other players taking pics of it, then automatically get the list shown into their app (e.g. Startactics). As an alternative they can share the URL on Whatsapp, FFG/BBG forums or Facebook from whatever App. This is far better than sharing json files.

**Comment by lvisintini** [comment]
@valeriodigregorio, I believe I misunderstood you previously.

I believed that you were saying you liked unique integer ids but I did not realise that you meant them to be unique across the whole dataset.

This I do not agree with on several accounts:
- Assigning unique integers is based on the order the entries are evaluated and not on the actual entry data, and it means that it would prone to error and difficult to maintain. At the very least, if I read `"lukeskywalker"` I can tell that it is related to one of two cards and, if we deprecate that code, we can create and maintain a mapping table with less effort.

- Making for short URLs is not within the scope of this project. Short URLs or permalinks a are engineering challenges that can be solved in a multitude of ways:
    - You can use a URL url shortener.
    - HMAC encryption algorithm could turn a long string into a short one like so:
```HMAC_MD5("key", "The quick brown fox jumps over the lazy dog")    = 80070713463e7749b90c2dc24911e275```
    - A website with a DB where users can store their list and link then directly.

-  If you are interested in using QR codes, then having short URLs is completely spurious

Regarding TTAdmiral's project:

TTAdmiral's code does not work with global unique ids. It has 2 sets of ids, one for command cards and another for deployments. They get added to the URL as double digit hexadecimal numbers and separated with a bunch of zeroes in the middle.

imperial-assault-data already has integer ids for both sets. All you would need to do to make their project use imperial-assault-data is to create a mapping table, but I don't feel like adding that to imperial-assault-data because I just feel that iaspec is a better solution.

Additionally, TTAdmiral's code has limitation of only being able to handle up 256 command cards and 256 deployment cards. Currently there is 161 deployment cards released and 206. We are not that far.
Either the code or the urls will have to change if we reach those limits.

**Comment by valeriodigregorio** [comment]
That's why I linked your project to the ttadmiral guy, with suggestion of using a more robust query string. We'll see what we can get!

**Comment by kingargyle** [comment]
Sorry for the delay, I'm fine with the enhancements to expand the data set useability of the iaspec.

**Comment by lvisintini** [comment]
Addressed in release [v1.0.5](https://github.com/lvisintini/imperial-assault-data/tree/v1.0.5)
