### ISSUE TITLE
Command card "Son of Skywalker" missing?

### ISSUE THREAD

**Issue by valeriodigregorio** [lvisintini/imperial-assault-data#9]
I can't find this: http://cards.boardwars.eu/albums/Core-Box/Command%20Cards/Son%20of%20Skywalker.jpg

**Comment by lvisintini** [comment]
Yeap, that is not included in the datased actually. thanks for spotting this.

When I scrapped the albums I neglected to follow up for additional pages in the command cards sub album......

Which is all really unfortunate because I though that I was done with the initial data load.
I will have to load it up in the next few weeks.

I missed scrapping at least this [page](http://cards.boardwars.eu/Core-Box/Command%20Cards/page/2/)
I may have missed others, but I will double check.

Sorry for the inconvenience. :(

**Comment by valeriodigregorio** [comment]
I asked the guy of the website to provide rest API, so you can now automate the process of checking what's missing. In case you haven't already done that, I scanned the website time ago to produce a spreadsheet that I then use for data mining when I build up skirmish lists:
https://docs.google.com/spreadsheets/d/12FeBA_aKu2rM90jLk-IrrWTeqpt3mJZ7TmhevNMwT5c
You can copy and paste the full list of card names and then cross check with what you currently have in JSON. You'll see duplicates in my list because some cards are actually duplicated across boxes and packs. Feel free to copy the spreadsheet if you want to do filtering and any other sort of mining (it's protected from editing).

**Comment by valeriodigregorio** [comment]
I counted 212 command cards. You have 189 in your json.  However I counted duplicates too.

**Comment by lvisintini** [comment]
I have found the error the crawler I coded up for http://cards.boardwars.eu
I found 17 additional command cards that I neglected.

**Comment by valeriodigregorio** [comment]
There are 6 dups indeed:
+1 Collect Intel
+2 Parting Blow
+1 Reinforcements
+1 Slippery Target
+1 Smuggled Supplies
which makes 189+17+6 == 212

**Comment by lvisintini** [comment]
Fixed in release [v1.0.4](https://github.com/lvisintini/imperial-assault-data/tree/v1.0.4)
